### ISSUE TITLE
多上 wechat， 少玩 github.

### ISSUE THREAD

**Issue by jiaobuzuji** [predisw/predisw.github.io#1]
多上 wechat， 少玩 github.

**Comment by predisw** [comment]
多上伤身，少玩怡情.

**Comment by jiaobuzuji** [comment]
Reopen Issue. **test 0**

**Comment by jiaobuzuji** [comment]
#1 @predisw 
Duplicate of #1

- [x] jsdgfe 
- [ ] jsdgfe sd 

If you are not a collaborator of a repo, then (in regards to issues)

you **can** open issues
you **can** comment on all existing issues (open or closed)
you **can** close your own issues
you **can** re-open your own issues *if you closed them yourself
you **cannot** close or re-open issues opened by someone else
you **cannot** re-open your own issues if a repo collaborator closed them

**test 1** Failure.
